[package]
name = "broadcast_3b"
version = "0.1.0"
edition = "2021"

[dependencies]
maelstrom = { path = "../maelstrom" }
anyhow = "1.0.79"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
